@baseUrl = https://localhost:7003

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "darren",
  "email": "darren@example.com"
}

###

### Get all users
GET {{baseUrl}}/users
Accept: application/json

###

### Get user by ID
# Replace this GUID with a real one from the create response
GET {{baseUrl}}/users/62196889-3b91-467f-9f4c-495839a72063
Accept: application/json

###

### Delete user by ID
DELETE {{baseUrl}}/users/62196889-3b91-467f-9f4c-495839a72063
Accept: application/json