@baseUrl = https://localhost:7003

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "darren",
  "email": "darren@example.com"
}

###

### Get all users
GET {{baseUrl}}/users
Accept: application/json

###

### Get user by ID
# Replace this GUID with a real one from the create response
GET {{baseUrl}}/users/1bd06c02-86ce-4a3f-8bea-9ee9e7798c9d
Accept: application/json

###

### Delete user by ID
DELETE {{baseUrl}}/users/1bd06c02-86ce-4a3f-8bea-9ee9e7798c9d
Accept: application/json